//
//  AKAccordionItem.h
//  AccordionKit
//
//  Copyright (c) 2010, Jeffrey Sambells / TropicalPixels.
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without 
//  modification, are permitted provided that the following conditions are met:
//  
//  Redistributions of source code must retain the above copyright notice, this 
//  list of conditions and the following disclaimer.
//  
//  Redistributions in binary form must reproduce the above copyright notice, 
//  this list of conditions and the following disclaimer in the documentation 
//  and/or other materials provided with the distribution.
//  
//  Neither the name of the <ORGANIZATION> nor the names of its contributors may 
//  be used to endorse or promote products derived from this software without 
//  specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
//  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
//  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
//  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
//  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
//  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
//  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
//  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
//  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
//  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
//  POSSIBILITY OF SUCH DAMAGE.

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

typedef enum {
    AKAccordionSystemItemFavorites,
    AKAccordionSystemItemFeatured,
    AKAccordionSystemItemTopRated,
    AKAccordionSystemItemRecents,
    AKAccordionSystemItemContacts,
    AKAccordionSystemItemHistory,
    AKAccordionSystemItemBookmarks,
    AKAccordionSystemItemSearch,
    AKAccordionSystemItemDownloads,
    AKAccordionSystemItemMostRecent,
    AKAccordionSystemItemMostViewed,
} AKAccordionSystemItem;

@interface AKAccordionItem : UIBarItem {
@private
    NSString     *_title;
    NSSet        *_possibleTitles;
    SEL           _action;
    id            _target;
    UIImage      *_image;
    UIImage      *_selectedImage;
    UIImage      *_unselectedImage;
    UIEdgeInsets  _imageInsets;
    NSString     *_badgeValue;
    UIView       *_view;
    NSInteger     _tag;
    struct {
		unsigned int enabled:1;
		unsigned int style:3;
		unsigned int isSystemItem:1;
		unsigned int systemItem:7;
		unsigned int viewIsCustom:1;
		unsigned int animatedBadge:1;
		unsigned int customSelectedImage:1;
		unsigned int customUnselectedImage:1;
    } _accordionItemFlags;
}

- (id)initWithTitle:(NSString *)title image:(UIImage *)image tag:(NSInteger)tag; // selected image autogenerated
- (id)initWithAccordionSystemItem:(AKAccordionSystemItem)systemItem tag:(NSInteger)tag;

@property(nonatomic,copy) NSString *badgeValue;    // default is nil

@end
